@HOSTNAME=http://localhost:5050/translations

GET {{HOSTNAME}}/project1

###
GET {{HOSTNAME}}/project2/test

###
POST {{HOSTNAME}}/project2
Content-Type: application/json

{
    "name": "prod"
}

###
PUT {{HOSTNAME}}/project3/test2
Content-Type: application/json

{
    "name": "test"
}

###
DELETE {{HOSTNAME}}/project3/prod2



