@HOSTNAME=http://localhost:5050/languages

GET {{HOSTNAME}}

###
GET {{HOSTNAME}}/8

###
POST {{HOSTNAME}}
Content-Type: application/json

{
    "languageCode": "test"
}

###
PUT {{HOSTNAME}}/10
Content-Type: application/json

{
    "languageCode": "test new"
}

###
DELETE {{HOSTNAME}}/10

