@HOSTNAME=http://localhost:5050/translations

GET {{HOSTNAME}}/project2/prod/en

###
POST {{HOSTNAME}}/project2/prod/en
###
PUT {{HOSTNAME}}/project2/prod/en
Content-Type: application/json

[
{
    "keyname": "k2",
    "translationText": "k2 translation update"
},
{
    "keyName": "k5",
    "translationText": "k5 translation update"
}
]

###
DELETE {{HOSTNAME}}/project2/prod/en


