@HOSTNAME=http://localhost:5050/translations

GET {{HOSTNAME}}/project1/test/

###
POST {{HOSTNAME}}/project1/test/cs
###
PUT {{HOSTNAME}}/project1/test/en
Content-Type: application/json

[
{
    "keyname": "key2",
    "translationText": "k2 translation update"
},
{
    "keyName": "key5",
    "translationText": "k5 translation update"
}
]

###
DELETE {{HOSTNAME}}/project1/test/en


